vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.showmode = true
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.signcolumn = "yes"
vim.opt.timeoutlen = 300
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.list = true
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
vim.opt.cursorline = true
vim.opt.scrolloff = 8
vim.o.sidescrolloff = 8
vim.opt.confirm = true
vim.o.swapfile = false
vim.o.wrap = false
vim.o.smartindent = true
vim.o.expandtab = true
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
vim.opt.termguicolors = true -- True color support
vim.opt.ttimeoutlen = 0 -- Faster escape key response
vim.opt.clipboard = "unnamedplus" -- Use system clipboard
vim.opt.completeopt = { "menuone", "noselect" } -- Better completion
vim.opt.pumheight = 10 -- Popup menu height
vim.o.winborder = "rounded"
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.have_nerd_font = true
