vim.o.number = true
vim.o.relativenumber = true
vim.o.mouse = "a"
vim.o.showmode = true
vim.o.breakindent = true
vim.o.undofile = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.signcolumn = "yes"
vim.o.timeoutlen = 300
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.list = true
vim.o.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
vim.o.cursorline = true
vim.o.scrolloff = 8
vim.o.sidescrolloff = 8
vim.o.confirm = true
vim.o.swapfile = false
vim.o.wrap = false
vim.o.smartindent = true
vim.o.expandtab = true
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
vim.o.termguicolors = true -- True color support
vim.o.ttimeoutlen = 0 -- Faster escape key response
vim.o.clipboard = "unnamedplus" -- Use system clipboard
vim.o.completeopt = { "menuone", "noselect" } -- Better completion
vim.o.pumheight = 10 -- Popup menu height
vim.o.winborder = "rounded"
vim.g.have_nerd_font = true
